// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../Gallery/dist/component.js', ['DD.ui.Component'], ['DD.ui.EventType', 'DD.ui.renderer.Component', 'goog.ui.Component', 'goog.ui.registry'], false);
goog.addDependency('../../../../Gallery/dist/componentrenderer.js', ['DD.ui.renderer.Component'], ['goog.array', 'goog.dom', 'goog.dom.classes', 'goog.style'], false);
goog.addDependency('../../../../Gallery/dist/flickslider.js', ['DD.ui.flickSliders.FlickSlider'], ['DD.ui.List', 'DD.ui.flickSliders', 'DD.ui.flickSliders.Slide', 'DD.ui.flickSliders.renderer.FlickSlider', 'goog.ui.registry'], false);
goog.addDependency('../../../../Gallery/dist/flicksliderrenderer.js', ['DD.ui.flickSliders.renderer.FlickSlider'], ['DD.ui.flickSliders.renderer', 'DD.ui.renderer.Component', 'goog.dom.classes'], false);
goog.addDependency('../../../../Gallery/dist/flicksliders.js', ['DD.ui.flickSliders', 'DD.ui.flickSliders.renderer'], [], false);
goog.addDependency('../../../../Gallery/dist/gallery.js', ['DD.ui.flickSliders.Gallery'], ['DD.ui.flickSliders.FlickSlider', 'DD.ui.flickSliders.renderer.Gallery', 'goog.ui.registry'], false);
goog.addDependency('../../../../Gallery/dist/list.js', ['DD.ui.List'], ['DD.ui.Component', 'DD.ui.EventType', 'DD.ui.renderer.List', 'goog.array', 'goog.events.Event', 'goog.ui.registry'], false);
goog.addDependency('../../../../Gallery/dist/listrenderer.js', ['DD.ui.renderer.List'], ['DD.ui.renderer.Component'], false);
goog.addDependency('../../../../Gallery/dist/renderer/galleryrenderer.js', ['DD.ui.flickSliders.renderer.Gallery'], ['DD.ui.flickSliders.renderer', 'DD.ui.renderer.Component', 'goog.dom.classes', 'goog.style.transform'], false);
goog.addDependency('../../../../Gallery/dist/slide/renderer/slide.js', ['DD.ui.flickSliders.renderer.Slide'], ['DD.ui.renderer.Component'], false);
goog.addDependency('../../../../Gallery/dist/slide/slide.js', ['DD.ui.flickSliders.Slide'], ['DD.ui.Component', 'DD.ui.flickSliders.renderer.Slide', 'goog.ui.registry'], false);
goog.addDependency('../../../../Gallery/dist/ui.js', ['DD.ui', 'DD.ui.EventType'], [], false);
